# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [192.168.240.2/24]
      gateway4: 192.168.240.1
      nameservers:
        addresses: [8.8.8.8,1.1.1.1]
  version: 2
